# target: prerequisites
#	command to build target

include ../../../common/Makefile

FLAG += -pthread

grandma_lotery: grandma_lotery.c
	cc -g -Wall -Wextra grandma_lotery.c -o grandma_lotery -pthread
