# target: prerequisites
#	command to build target

include ../../../common/Makefile

FLAG += -pthread

recursive_hello: recursive_hello.c
	cc -g -Wall -Wextra recursive_hello.c -o recursive_hello -pthread